export interface MetricWidget {
  id: string;
  label: string;
  description?: string;
}

export interface MetricCategory {
  id: string;
  label: string;
  count: number;
  hasInfo?: boolean;
  widgets: MetricWidget[];
}

export const METRICS_CATEGORIES: MetricCategory[] = [
  {
    id: 'jobs',
    label: 'Jobs',
    count: 15,
    widgets: [
      { id: 'jobs-total', label: 'Total Jobs' },
      { id: 'jobs-created', label: 'Jobs Created' },
      { id: 'jobs-completed', label: 'Jobs Completed' },
      { id: 'jobs-in-progress', label: 'Jobs In Progress' },
      { id: 'jobs-scheduled', label: 'Jobs Scheduled' },
      { id: 'jobs-lost', label: 'Jobs Lost' },
      { id: 'jobs-won', label: 'Jobs Won' },
      { id: 'jobs-cancelled', label: 'Jobs Cancelled' },
      { id: 'jobs-by-stage', label: 'Jobs by Stage' },
      { id: 'jobs-avg-value', label: 'Average Job Value' },
      { id: 'jobs-total-value', label: 'Total Job Value' },
      { id: 'jobs-materials-ordered', label: 'Materials Ordered Jobs' },
      { id: 'jobs-started', label: 'Jobs Started' },
      { id: 'jobs-awaiting-invoice', label: 'Jobs Awaiting Invoice' },
      { id: 'jobs-invoiced', label: 'Jobs Invoiced' },
    ],
  },
  {
    id: 'appointments',
    label: 'Appointments',
    count: 15,
    widgets: [
      { id: 'appointments-total', label: 'Total Appointments' },
      { id: 'appointments-booked', label: 'Appointments Booked' },
      { id: 'appointments-completed', label: 'Appointments Completed' },
      { id: 'appointments-no-show', label: 'Appointments No-Show' },
      { id: 'appointments-conversion-rate', label: 'Appointment Conversion Rate' },
      { id: 'appointments-source-breakdown', label: 'Appointment Source Breakdown' },
      { id: 'appointments-type-breakdown', label: 'Appointment Type Breakdown' },
      { id: 'appointments-cancellations', label: 'Appointment Cancellations' },
      { id: 'appointments-first-time', label: 'First-Time Appointments' },
      { id: 'appointments-repeat', label: 'Repeat Appointments' },
      { id: 'appointments-avg-time-to-first', label: 'Avg Time to First Appointment' },
      { id: 'appointments-per-sales-rep', label: 'Appointments per Sales Rep' },
      { id: 'appointments-per-lead-source', label: 'Appointments per Lead Source' },
      { id: 'appointments-daily-trend', label: 'Daily Appointment Trend' },
      { id: 'appointments-pipeline-flow', label: 'Appointment Pipeline Flow' },
    ],
  },
  {
    id: 'opportunities',
    label: 'Opportunities',
    count: 17,
    widgets: [
      { id: 'opportunities-total', label: 'Total Opportunities' },
      { id: 'opportunities-new', label: 'New Opportunities' },
      { id: 'opportunities-by-stage', label: 'Opportunities by Stage' },
      { id: 'opportunities-closed-won', label: 'Closed Won' },
      { id: 'opportunities-closed-lost', label: 'Closed Lost' },
      { id: 'opportunities-pipeline-value', label: 'Pipeline Value' },
      { id: 'opportunities-avg-deal-size', label: 'Average Deal Size' },
      { id: 'opportunities-conversion-rate', label: 'Opportunity Conversion Rate' },
      { id: 'opportunities-by-source', label: 'Opportunities by Source' },
      { id: 'opportunities-by-rep', label: 'Opportunities by Rep' },
      { id: 'opportunities-created-per-day', label: 'Opportunities Created per Day' },
      { id: 'opportunities-requiring-follow-up', label: 'Opportunities Requiring Follow-Up' },
      { id: 'opportunities-overdue', label: 'Overdue Opportunities' },
      { id: 'opportunities-conversion-velocity', label: 'Conversion Velocity (Days to Close)' },
      { id: 'opportunities-win-rate', label: 'Opportunity Win Rate' },
      { id: 'opportunities-lost-reason', label: 'Lost Reason Breakdown' },
      { id: 'opportunities-weighted-pipeline', label: 'Weighted Pipeline Value' },
    ],
  },
  {
    id: 'visitor-data',
    label: 'Visitor Data',
    count: 13,
    widgets: [
      { id: 'visitor-total', label: 'Total Website Visitors' },
      { id: 'visitor-unique', label: 'Unique Visitors' },
      { id: 'visitor-returning', label: 'Returning Visitors' },
      { id: 'visitor-page-views', label: 'Page Views' },
      { id: 'visitor-avg-session-duration', label: 'Avg Session Duration' },
      { id: 'visitor-bounce-rate', label: 'Bounce Rate' },
      { id: 'visitor-form-submissions', label: 'Form Submissions' },
      { id: 'visitor-chat-conversations', label: 'Chat Widget Conversations' },
      { id: 'visitor-click-to-call', label: 'Click-to-Call Events' },
      { id: 'visitor-lead-conversion-rate', label: 'Lead Conversion Rate' },
      { id: 'visitor-utm-source-breakdown', label: 'UTM Source Breakdown' },
      { id: 'visitor-traffic-by-device', label: 'Traffic by Device' },
      { id: 'visitor-traffic-by-time', label: 'Traffic by Time of Day' },
    ],
  },
  {
    id: 'emails',
    label: 'Emails',
    count: 11,
    widgets: [
      { id: 'emails-sent', label: 'Emails Sent' },
      { id: 'emails-delivered', label: 'Emails Delivered' },
      { id: 'emails-opens', label: 'Email Opens' },
      { id: 'emails-open-rate', label: 'Email Open Rate' },
      { id: 'emails-click-rate', label: 'Email Click Rate' },
      { id: 'emails-replies', label: 'Email Replies' },
      { id: 'emails-bounces', label: 'Email Bounces' },
      { id: 'emails-unsubscribes', label: 'Email Unsubscribes' },
      { id: 'emails-automation-triggers', label: 'Email Automation Triggers' },
      { id: 'emails-by-campaign', label: 'Emails by Campaign' },
      { id: 'emails-performance-score', label: 'Email Performance Score' },
    ],
  },
  {
    id: 'calls',
    label: 'Calls',
    count: 13,
    widgets: [
      { id: 'calls-total', label: 'Total Calls' },
      { id: 'calls-outbound', label: 'Outbound Calls' },
      { id: 'calls-inbound', label: 'Inbound Calls' },
      { id: 'calls-missed', label: 'Missed Calls' },
      { id: 'calls-answered', label: 'Answered Calls' },
      { id: 'calls-voicemails', label: 'Voicemails' },
      { id: 'calls-duration-avg', label: 'Call Duration Avg' },
      { id: 'calls-by-rep', label: 'Calls by Rep' },
      { id: 'calls-by-source', label: 'Calls by Source' },
      { id: 'calls-first-call-resolution', label: 'First-Call Resolution' },
      { id: 'calls-conversion-to-appointment', label: 'Call Conversion to Appointment' },
      { id: 'calls-caller-id-breakdown', label: 'Caller ID Breakdown' },
      { id: 'calls-outcomes', label: 'Call Outcomes' },
    ],
  },
  {
    id: 'conversations',
    label: 'Conversations',
    count: 12,
    widgets: [
      { id: 'conversations-total', label: 'Total Conversations' },
      { id: 'conversations-new', label: 'New Conversations' },
      { id: 'conversations-open', label: 'Open Conversations' },
      { id: 'conversations-closed', label: 'Closed Conversations' },
      { id: 'conversations-response-time-avg', label: 'Response Time Avg' },
      { id: 'conversations-first-reply-time', label: 'First Reply Time' },
      { id: 'conversations-channel-breakdown', label: 'Conversation Channel Breakdown' },
      { id: 'conversations-sms-sent', label: 'SMS Sent' },
      { id: 'conversations-sms-delivered', label: 'SMS Delivered' },
      { id: 'conversations-sms-replies', label: 'SMS Replies' },
      { id: 'conversations-chatbot-interactions', label: 'Chatbot Interactions' },
      { id: 'conversations-to-lead-conversion', label: 'Conversation-to-Lead Conversion' },
    ],
  },
  {
    id: 'payments',
    label: 'Payments',
    count: 17,
    widgets: [
      { id: 'payments-total-collected', label: 'Total Payments Collected' },
      { id: 'payments-pending', label: 'Pending Payments' },
      { id: 'payments-overdue', label: 'Overdue Payments' },
      { id: 'payments-failed', label: 'Failed Payments' },
      { id: 'payments-partial', label: 'Partial Payments' },
      { id: 'payments-avg-value', label: 'Avg Payment Value' },
      { id: 'payments-methods-used', label: 'Payment Methods Used' },
      { id: 'payments-total-invoiced', label: 'Total Invoiced Amount' },
      { id: 'payments-outstanding-invoice', label: 'Outstanding Invoice Total' },
      { id: 'payments-collection-rate', label: 'Payment Collection Rate' },
      { id: 'payments-refunds-issued', label: 'Refunds Issued' },
      { id: 'payments-deposits-collected', label: 'Deposits Collected' },
      { id: 'payments-by-job', label: 'Payment by Job' },
      { id: 'payments-by-sales-rep', label: 'Payment by Sales Rep' },
      { id: 'payments-by-customer', label: 'Payment by Customer' },
      { id: 'payments-timing', label: 'Payment Timing (Days to Pay)' },
      { id: 'payments-trend-line', label: 'Payment Trend Line' },
    ],
  },
  {
    id: 'meta-ads',
    label: 'Meta Ads',
    count: 16,
    widgets: [
      { id: 'meta-ads-total-spend', label: 'Total Spend' },
      { id: 'meta-ads-impressions', label: 'Impressions' },
      { id: 'meta-ads-clicks', label: 'Clicks' },
      { id: 'meta-ads-ctr', label: 'CTR' },
      { id: 'meta-ads-cpc', label: 'CPC' },
      { id: 'meta-ads-cpm', label: 'CPM' },
      { id: 'meta-ads-leads-generated', label: 'Leads Generated' },
      { id: 'meta-ads-cost-per-lead', label: 'Cost per Lead' },
      { id: 'meta-ads-cost-per-appointment', label: 'Cost per Appointment' },
      { id: 'meta-ads-frequency', label: 'Ad Frequency' },
      { id: 'meta-ads-landing-page-conversion', label: 'Landing Page Conversion Rate' },
      { id: 'meta-ads-form-completion', label: 'Form Completion Rate' },
      { id: 'meta-ads-by-campaign', label: 'Ads by Campaign' },
      { id: 'meta-ads-best-performing-creative', label: 'Best Performing Creative' },
      { id: 'meta-ads-roas', label: 'ROAS' },
      { id: 'meta-ads-lead-quality-score', label: 'Lead Quality Score' },
    ],
  },
  {
    id: 'general',
    label: 'General',
    count: 14,
    hasInfo: true,
    widgets: [
      { id: 'general-total-contacts', label: 'Total Contacts' },
      { id: 'general-new-contacts', label: 'New Contacts' },
      { id: 'general-duplicate-contacts', label: 'Duplicate Contacts' },
      { id: 'general-contact-source-breakdown', label: 'Contact Source Breakdown' },
      { id: 'general-new-leads', label: 'New Leads' },
      { id: 'general-lead-to-opportunity-rate', label: 'Lead-to-Opportunity Rate' },
      { id: 'general-crm-activity-count', label: 'CRM Activity Count' },
      { id: 'general-tasks-created', label: 'Tasks Created' },
      { id: 'general-tasks-completed', label: 'Tasks Completed' },
      { id: 'general-reminders-overdue', label: 'Reminders Overdue' },
      { id: 'general-automations-triggered', label: 'Automations Triggered' },
      { id: 'general-users-active', label: 'Users Active' },
      { id: 'general-team-performance-overview', label: 'Team Performance Overview' },
      { id: 'general-system-health-metrics', label: 'System Health Metrics' },
    ],
  },
  {
    id: 'analytics',
    label: 'Analytics',
    count: 18,
    widgets: [
      { id: 'analytics-global-funnel-conversion', label: 'Global Funnel Conversion Rate' },
      { id: 'analytics-acquisition-cost', label: 'Acquisition Cost Across Channels' },
      { id: 'analytics-channel-performance', label: 'Channel Performance Comparison' },
      { id: 'analytics-lead-velocity-rate', label: 'Lead Velocity Rate' },
      { id: 'analytics-revenue-forecast', label: 'Revenue Forecast' },
      { id: 'analytics-revenue-per-lead', label: 'Revenue per Lead' },
      { id: 'analytics-revenue-per-job', label: 'Revenue per Job' },
      { id: 'analytics-lost-revenue', label: 'Lost Revenue (Job Losses)' },
      { id: 'analytics-follow-up-performance', label: 'Follow-Up Performance' },
      { id: 'analytics-automations-performance', label: 'Automations Performance Score' },
      { id: 'analytics-attribution-model', label: 'Attribution Model Breakdown' },
      { id: 'analytics-heatmap-time-of-day', label: 'Heatmap by Time of Day' },
      { id: 'analytics-heatmap-weekday', label: 'Heatmap by Weekday' },
      { id: 'analytics-ga4-data-imports', label: 'GA4 Data Imports' },
      { id: 'analytics-cross-channel-roi', label: 'Cross-Channel ROI' },
      { id: 'analytics-multi-touch-attribution', label: 'Multi-Touch Attribution' },
      { id: 'analytics-customer-lifetime-value', label: 'Customer Lifetime Value' },
      { id: 'analytics-cost-per-acquisition', label: 'Cost per Acquisition' },
    ],
  },
];
