/*
  # Create AI Proposal Sections Staging Table

  ## Purpose
  Provides a lightweight staging area for AI-generated proposal sections. Each row represents
  one content section generated by the AI for a specific proposal. Sections are written here
  during generation and then merged into the parent proposal's content JSONB field.

  ## New Tables
  - `ai_proposal_sections_staging`
    - `id` (uuid, primary key)
    - `organization_id` (uuid) - multi-tenant scoping
    - `proposal_id` (uuid) - parent proposal reference
    - `section_type` (text) - e.g. 'intro', 'scope', 'materials', 'timeline', 'terms', 'damage_assessment', 'custom'
    - `title` (text) - section heading shown in the builder
    - `content` (text) - HTML content generated by the AI
    - `sort_order` (integer) - display ordering for sections
    - `ai_generated` (boolean, default true) - marks sections as AI-authored
    - `created_at` (timestamptz)

  ## Security
  - RLS enabled
  - Authenticated users can SELECT/INSERT/UPDATE/DELETE their own org's sections
  - Policies check organization_id matches user's own organizations

  ## Notes
  - No hard FK to proposals since proposals table may not exist yet in all environments
  - The table is intentionally simple; complex state lives in the proposals.content JSONB field
*/

CREATE TABLE IF NOT EXISTS ai_proposal_sections_staging (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  proposal_id uuid NOT NULL,
  section_type text NOT NULL DEFAULT 'custom',
  title text NOT NULL DEFAULT '',
  content text NOT NULL DEFAULT '',
  sort_order integer NOT NULL DEFAULT 0,
  ai_generated boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_proposal_sections_staging_proposal_id
  ON ai_proposal_sections_staging(proposal_id);

CREATE INDEX IF NOT EXISTS idx_ai_proposal_sections_staging_org_id
  ON ai_proposal_sections_staging(organization_id);

ALTER TABLE ai_proposal_sections_staging ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members can view ai proposal sections"
  ON ai_proposal_sections_staging FOR SELECT
  TO authenticated
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "Org members can insert ai proposal sections"
  ON ai_proposal_sections_staging FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Org members can update ai proposal sections"
  ON ai_proposal_sections_staging FOR UPDATE
  TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Org members can delete ai proposal sections"
  ON ai_proposal_sections_staging FOR DELETE
  TO authenticated
  USING (auth.uid() IS NOT NULL);
